/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_PRIVATEIMPORT_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjCContainerFoundation_import_private_h__
#define _MulleObjCContainerFoundation_import_private_h__

/* no headers */

#ifdef __has_include
# if __has_include( "_MulleObjCContainerFoundation-include.h")
#  include "_MulleObjCContainerFoundation-include-private.h"
# endif
#endif

#endif
