      { @selector( MulleObjCArrayReverseEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 1f04617c;MulleObjCArrayReverseEnumerator;;
      { @selector( NSArray), @selector( MulleMutableArrayAdditions) },      // 233490fe;NSArray;06c6446f;MulleMutableArrayAdditions
      { @selector( NSArray), @selector( NSCoder) },      // 233490fe;NSArray;100c54ba;NSCoder
      { @selector( NSArray), @selector( NSMutableCopying) },      // 233490fe;NSArray;4aa86031;NSMutableCopying
      { @selector( NSArray), MULLE_OBJC_NO_CATEGORYID },      // 233490fe;NSArray;;
      { @selector( NSDictionary), @selector( NSArray) },      // 8b2abcad;NSDictionary;233490fe;NSArray
      { @selector( NSDictionary), @selector( NSCoder) },      // 8b2abcad;NSDictionary;100c54ba;NSCoder
      { @selector( NSDictionary), @selector( NSMutableDictionary) },      // 8b2abcad;NSDictionary;2f2fa84a;NSMutableDictionary
      { @selector( NSDictionary), MULLE_OBJC_NO_CATEGORYID },      // 8b2abcad;NSDictionary;;
      { @selector( NSEnumerator), @selector( NSArray) },      // e631d30d;NSEnumerator;233490fe;NSArray
      { @selector( NSEnumerator), MULLE_OBJC_NO_CATEGORYID },      // e631d30d;NSEnumerator;;
      { @selector( NSMutableArray), @selector( NSCoder) },      // f5e6dbdd;NSMutableArray;100c54ba;NSCoder
      { @selector( NSMutableArray), @selector( NSSet) },      // f5e6dbdd;NSMutableArray;9f69e3e4;NSSet
      { @selector( NSMutableArray), MULLE_OBJC_NO_CATEGORYID },      // f5e6dbdd;NSMutableArray;;
      { @selector( NSMutableDictionary), @selector( NSArray) },      // 2f2fa84a;NSMutableDictionary;233490fe;NSArray
      { @selector( NSMutableDictionary), @selector( NSCoder) },      // 2f2fa84a;NSMutableDictionary;100c54ba;NSCoder
      { @selector( NSMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2f2fa84a;NSMutableDictionary;;
      { @selector( NSMutableSet), @selector( NSArray) },      // 1fa72100;NSMutableSet;233490fe;NSArray
      { @selector( NSMutableSet), @selector( NSCoder) },      // 1fa72100;NSMutableSet;100c54ba;NSCoder
      { @selector( NSMutableSet), MULLE_OBJC_NO_CATEGORYID },      // 1fa72100;NSMutableSet;;
      { @selector( NSObject), @selector( _NSArray) },      // b3a66256;NSObject;0beba328;_NSArray
      { @selector( NSObject), @selector( _NSDictionary) },      // b3a66256;NSObject;413cd390;_NSDictionary
      { @selector( NSObject), @selector( _NSMutableArray) },      // b3a66256;NSObject;2f8adfe0;_NSMutableArray
      { @selector( NSObject), @selector( _NSMutableDictionary) },      // b3a66256;NSObject;1f96dfdd;_NSMutableDictionary
      { @selector( NSObject), @selector( _NSSet) },      // b3a66256;NSObject;2f766bf1;_NSSet
      { @selector( NSSet), @selector( NSArray) },      // 9f69e3e4;NSSet;233490fe;NSArray
      { @selector( NSSet), @selector( NSCoder) },      // 9f69e3e4;NSSet;100c54ba;NSCoder
      { @selector( NSSet), @selector( NSMutableSet) },      // 9f69e3e4;NSSet;1fa72100;NSMutableSet
      { @selector( NSSet), MULLE_OBJC_NO_CATEGORYID },      // 9f69e3e4;NSSet;;
      { @selector( NSThread), @selector( NSDictionary) },      // c81b9c22;NSThread;8b2abcad;NSDictionary
      { @selector( _MulleObjCArrayEnumerator), MULLE_OBJC_NO_CATEGORYID },      // b826ca4d;_MulleObjCArrayEnumerator;;
      { @selector( _MulleObjCConcreteArray), @selector( NSCoder) },      // 3610e4bd;_MulleObjCConcreteArray;100c54ba;NSCoder
      { @selector( _MulleObjCConcreteArray), MULLE_OBJC_NO_CATEGORYID },      // 3610e4bd;_MulleObjCConcreteArray;;
      { @selector( _MulleObjCConcreteDictionary), MULLE_OBJC_NO_CATEGORYID },      // aa37b8ec;_MulleObjCConcreteDictionary;;
      { @selector( _MulleObjCConcreteMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2ce9638f;_MulleObjCConcreteMutableDictionary;;
      { @selector( _MulleObjCConcreteMutableSet), MULLE_OBJC_NO_CATEGORYID },      // b7eb37c0;_MulleObjCConcreteMutableSet;;
      { @selector( _MulleObjCConcreteSet), MULLE_OBJC_NO_CATEGORYID },      // 2823d0a0;_MulleObjCConcreteSet;;
      { @selector( _MulleObjCDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2b722f90;_MulleObjCDictionary;;
      { @selector( _MulleObjCDictionaryKeyEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 047702a5;_MulleObjCDictionaryKeyEnumerator;;
      { @selector( _MulleObjCDictionaryObjectEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 49965c09;_MulleObjCDictionaryObjectEnumerator;;
      { @selector( _MulleObjCEmptyArray), MULLE_OBJC_NO_CATEGORYID },      // 7aa0d636;_MulleObjCEmptyArray;;
      { @selector( _MulleObjCEmptyDictionary), @selector( NSCoder) },      // cc5dc56a;_MulleObjCEmptyDictionary;100c54ba;NSCoder
      { @selector( _MulleObjCEmptyDictionary), MULLE_OBJC_NO_CATEGORYID },      // cc5dc56a;_MulleObjCEmptyDictionary;;
      { @selector( _MulleObjCEmptySet), @selector( NSCoder) },      // b4c55b26;_MulleObjCEmptySet;100c54ba;NSCoder
      { @selector( _MulleObjCEmptySet), MULLE_OBJC_NO_CATEGORYID },      // b4c55b26;_MulleObjCEmptySet;;
      { @selector( _MulleObjCSet), MULLE_OBJC_NO_CATEGORYID },      // 5da537fa;_MulleObjCSet;;
      { @selector( _MulleObjCSetEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 832b431a;_MulleObjCSetEnumerator;;
      { @selector( _NSArrayPlaceholder), @selector( NSCoder) },      // 43057f70;_NSArrayPlaceholder;100c54ba;NSCoder
      { @selector( _NSArrayPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 43057f70;_NSArrayPlaceholder;;
      { @selector( _NSDictionaryPlaceholder), @selector( NSCoder) },      // 28e52164;_NSDictionaryPlaceholder;100c54ba;NSCoder
      { @selector( _NSDictionaryPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 28e52164;_NSDictionaryPlaceholder;;
      { @selector( _NSMutableDictionaryPlaceholder), @selector( NSCoder) },      // 74c8de28;_NSMutableDictionaryPlaceholder;100c54ba;NSCoder
      { @selector( _NSMutableDictionaryPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 74c8de28;_NSMutableDictionaryPlaceholder;;
      { @selector( _NSMutableSetPlaceholder), @selector( NSCoder) },      // f133938c;_NSMutableSetPlaceholder;100c54ba;NSCoder
      { @selector( _NSMutableSetPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // f133938c;_NSMutableSetPlaceholder;;
      { @selector( _NSSetPlaceholder), @selector( NSCoder) },      // 5929a24b;_NSSetPlaceholder;100c54ba;NSCoder
      { @selector( _NSSetPlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 5929a24b;_NSSetPlaceholder;;
