      { @selector( MulleObjCArchiver), MULLE_OBJC_NO_CATEGORYID },      // dbbd06ce;MulleObjCArchiver;;
      { @selector( MulleObjCArrayReverseEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 4e90599f;MulleObjCArrayReverseEnumerator;;
      { @selector( MulleObjCUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 6a4e784f;MulleObjCUnarchiver;;
      { @selector( MulleObjCUnkeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 6651b187;MulleObjCUnkeyedArchiver;;
      { @selector( MulleObjCUnkeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 1192b722;MulleObjCUnkeyedUnarchiver;;
      { @selector( NSArchiver), MULLE_OBJC_NO_CATEGORYID },      // 3140e86c;NSArchiver;;
      { @selector( NSArray), @selector( NSCoder) },      // 55e6335f;NSArray;57eb31d7;NSCoder
      { @selector( NSArray), @selector( NSLocale) },      // 55e6335f;NSArray;60293bce;NSLocale
      { @selector( NSArray), @selector( NSMutableCopying) },      // 55e6335f;NSArray;e5a2a39b;NSMutableCopying
      { @selector( NSArray), @selector( NSPropertyListParsing) },      // 55e6335f;NSArray;d53dd685;NSPropertyListParsing
      { @selector( NSArray), @selector( NSSortDescriptor) },      // 55e6335f;NSArray;115836cf;NSSortDescriptor
      { @selector( NSArray), @selector( NSString) },      // 55e6335f;NSArray;85e3fa43;NSString
      { @selector( NSArray), @selector( PropertyListPrinting) },      // 55e6335f;NSArray;1cb22f11;PropertyListPrinting
      { @selector( NSArray), MULLE_OBJC_NO_CATEGORYID },      // 55e6335f;NSArray;;
      { @selector( NSAssertionHandler), MULLE_OBJC_NO_CATEGORYID },      // ae7c3830;NSAssertionHandler;;
      { @selector( NSCalendarDate), @selector( NSDateFormatter) },      // 732630c6;NSCalendarDate;baad3d86;NSDateFormatter
      { @selector( NSCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // 732630c6;NSCalendarDate;;
      { @selector( NSCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // b452f5f7;NSCharacterSet;;
      { @selector( NSCoder), MULLE_OBJC_NO_CATEGORYID },      // 57eb31d7;NSCoder;;
      { @selector( NSConstantString), MULLE_OBJC_NO_CATEGORYID },      // 83ca6a67;NSConstantString;;
      { @selector( NSData), @selector( NSCoder) },      // 7d1455e8;NSData;57eb31d7;NSCoder
      { @selector( NSData), @selector( NSMutableCopying) },      // 7d1455e8;NSData;e5a2a39b;NSMutableCopying
      { @selector( NSData), @selector( NSPropertyListParsing) },      // 7d1455e8;NSData;d53dd685;NSPropertyListParsing
      { @selector( NSData), @selector( NSString) },      // 7d1455e8;NSData;85e3fa43;NSString
      { @selector( NSData), @selector( PropertyListPrinting) },      // 7d1455e8;NSData;1cb22f11;PropertyListPrinting
      { @selector( NSData), @selector( _Unicode) },      // 7d1455e8;NSData;b9067a61;_Unicode
      { @selector( NSData), MULLE_OBJC_NO_CATEGORYID },      // 7d1455e8;NSData;;
      { @selector( NSDate), @selector( NSCalendarDate) },      // 7d1455ec;NSDate;732630c6;NSCalendarDate
      { @selector( NSDate), @selector( NSCoder) },      // 7d1455ec;NSDate;57eb31d7;NSCoder
      { @selector( NSDate), @selector( NSDateFormatter) },      // 7d1455ec;NSDate;baad3d86;NSDateFormatter
      { @selector( NSDate), @selector( PropertyListPrinting) },      // 7d1455ec;NSDate;1cb22f11;PropertyListPrinting
      { @selector( NSDate), MULLE_OBJC_NO_CATEGORYID },      // 7d1455ec;NSDate;;
      { @selector( NSDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // baad3d86;NSDateFormatter;;
      { @selector( NSDictionary), @selector( NSArray) },      // ca46313c;NSDictionary;55e6335f;NSArray
      { @selector( NSDictionary), @selector( NSCoder) },      // ca46313c;NSDictionary;57eb31d7;NSCoder
      { @selector( NSDictionary), @selector( NSLocale) },      // ca46313c;NSDictionary;60293bce;NSLocale
      { @selector( NSDictionary), @selector( NSMutableDictionary) },      // ca46313c;NSDictionary;edeb2f5a;NSMutableDictionary
      { @selector( NSDictionary), @selector( NSPropertyListParsing) },      // ca46313c;NSDictionary;d53dd685;NSPropertyListParsing
      { @selector( NSDictionary), @selector( NSString) },      // ca46313c;NSDictionary;85e3fa43;NSString
      { @selector( NSDictionary), @selector( PropertyListPrinting) },      // ca46313c;NSDictionary;1cb22f11;PropertyListPrinting
      { @selector( NSDictionary), MULLE_OBJC_NO_CATEGORYID },      // ca46313c;NSDictionary;;
      { @selector( NSEnumerator), @selector( NSArray) },      // 3ff70b6e;NSEnumerator;55e6335f;NSArray
      { @selector( NSEnumerator), @selector( Perform) },      // 3ff70b6e;NSEnumerator;d7dcdc48;Perform
      { @selector( NSEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 3ff70b6e;NSEnumerator;;
      { @selector( NSError), MULLE_OBJC_NO_CATEGORYID },      // d49f3e12;NSError;;
      { @selector( NSException), @selector( String) },      // a41284db;NSException;97be4a2e;String
      { @selector( NSException), MULLE_OBJC_NO_CATEGORYID },      // a41284db;NSException;;
      { @selector( NSFormatter), MULLE_OBJC_NO_CATEGORYID },      // 40625392;NSFormatter;;
      { @selector( NSKeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 028c2ebe;NSKeyedArchiver;;
      { @selector( NSKeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // e7d1c4df;NSKeyedUnarchiver;;
      { @selector( NSLocale), MULLE_OBJC_NO_CATEGORYID },      // 60293bce;NSLocale;;
      { @selector( NSLock), @selector( NSDate) },      // ccba22ad;NSLock;7d1455ec;NSDate
      { @selector( NSMethodSignature), @selector( NSString) },      // 6901a863;NSMethodSignature;85e3fa43;NSString
      { @selector( NSMutableArray), @selector( NSCoder) },      // 33fb2e49;NSMutableArray;57eb31d7;NSCoder
      { @selector( NSMutableArray), @selector( NSSortDescriptor) },      // 33fb2e49;NSMutableArray;115836cf;NSSortDescriptor
      { @selector( NSMutableArray), MULLE_OBJC_NO_CATEGORYID },      // 33fb2e49;NSMutableArray;;
      { @selector( NSMutableData), @selector( NSCoder) },      // 80af06be;NSMutableData;57eb31d7;NSCoder
      { @selector( NSMutableData), @selector( _MulleObjCOutputDataStream) },      // 80af06be;NSMutableData;a6b09746;_MulleObjCOutputDataStream
      { @selector( NSMutableData), MULLE_OBJC_NO_CATEGORYID },      // 80af06be;NSMutableData;;
      { @selector( NSMutableDictionary), @selector( NSArray) },      // edeb2f5a;NSMutableDictionary;55e6335f;NSArray
      { @selector( NSMutableDictionary), @selector( NSCoder) },      // edeb2f5a;NSMutableDictionary;57eb31d7;NSCoder
      { @selector( NSMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // edeb2f5a;NSMutableDictionary;;
      { @selector( NSMutableSet), @selector( NSArray) },      // e6cae1ee;NSMutableSet;55e6335f;NSArray
      { @selector( NSMutableSet), @selector( NSCoder) },      // e6cae1ee;NSMutableSet;57eb31d7;NSCoder
      { @selector( NSMutableSet), MULLE_OBJC_NO_CATEGORYID },      // e6cae1ee;NSMutableSet;;
      { @selector( NSMutableString), @selector( NSData) },      // fcaa2a91;NSMutableString;7d1455e8;NSData
      { @selector( NSMutableString), MULLE_OBJC_NO_CATEGORYID },      // fcaa2a91;NSMutableString;;
      { @selector( NSNotification), MULLE_OBJC_NO_CATEGORYID },      // 18e88d95;NSNotification;;
      { @selector( NSNotificationCenter), MULLE_OBJC_NO_CATEGORYID },      // 385d8f76;NSNotificationCenter;;
      { @selector( NSNull), MULLE_OBJC_NO_CATEGORYID },      // d33643ef;NSNull;;
      { @selector( NSNumber), @selector( NSCoder) },      // 1fa441bb;NSNumber;57eb31d7;NSCoder
      { @selector( NSNumber), @selector( NSLocale) },      // 1fa441bb;NSNumber;60293bce;NSLocale
      { @selector( NSNumber), @selector( NSString) },      // 1fa441bb;NSNumber;85e3fa43;NSString
      { @selector( NSNumber), @selector( PropertyListPrinting) },      // 1fa441bb;NSNumber;1cb22f11;PropertyListPrinting
      { @selector( NSNumber), MULLE_OBJC_NO_CATEGORYID },      // 1fa441bb;NSNumber;;
      { @selector( NSNumberFormatter), MULLE_OBJC_NO_CATEGORYID },      // 883530b3;NSNumberFormatter;;
      { @selector( NSObject), @selector( NSCoder) },      // e9e78cbd;NSObject;57eb31d7;NSCoder
      { @selector( NSObject), @selector( NSPropertyListParsing) },      // e9e78cbd;NSObject;d53dd685;NSPropertyListParsing
      { @selector( NSObject), @selector( NSString) },      // e9e78cbd;NSObject;85e3fa43;NSString
      { @selector( NSObject), @selector( PropertyListPrinting) },      // e9e78cbd;NSObject;1cb22f11;PropertyListPrinting
      { @selector( NSObject), @selector( _NSArray) },      // e9e78cbd;NSObject;f49cb130;_NSArray
      { @selector( NSObject), @selector( _NSCalendarDate) },      // e9e78cbd;NSObject;2eef2477;_NSCalendarDate
      { @selector( NSObject), @selector( _NSData) },      // e9e78cbd;NSObject;fa6e9c31;_NSData
      { @selector( NSObject), @selector( _NSDate) },      // e9e78cbd;NSObject;fa6e9c35;_NSDate
      { @selector( NSObject), @selector( _NSDictionary) },      // e9e78cbd;NSObject;5ecb4561;_NSDictionary
      { @selector( NSObject), @selector( _NSLocale) },      // e9e78cbd;NSObject;776e7caf;_NSLocale
      { @selector( NSObject), @selector( _NSMutableData) },      // e9e78cbd;NSObject;bafcf24d;_NSMutableData
      { @selector( NSObject), @selector( _NSMutableDictionary) },      // e9e78cbd;NSObject;d788570d;_NSMutableDictionary
      { @selector( NSObject), @selector( _NSMutableString) },      // e9e78cbd;NSObject;a2572c1e;_NSMutableString
      { @selector( NSObject), @selector( _NSNull) },      // e9e78cbd;NSObject;b44b34ea;_NSNull
      { @selector( NSObject), @selector( _NSNumber) },      // e9e78cbd;NSObject;05c62dfe;_NSNumber
      { @selector( NSObject), @selector( _NSSet) },      // e9e78cbd;NSObject;ef0424f3;_NSSet
      { @selector( NSObject), @selector( _NSString) },      // e9e78cbd;NSObject;f080ce2a;_NSString
      { @selector( NSObject), @selector( _NSTimeZone) },      // e9e78cbd;NSObject;32e5e7e4;_NSTimeZone
      { @selector( NSObject), @selector( _NSValue) },      // e9e78cbd;NSObject;227bb908;_NSValue
      { @selector( NSPropertyListSerialization), MULLE_OBJC_NO_CATEGORYID },      // 6a96a095;NSPropertyListSerialization;;
      { @selector( NSScanner), MULLE_OBJC_NO_CATEGORYID },      // baff1492;NSScanner;;
      { @selector( NSSet), @selector( NSArray) },      // 9a5ad940;NSSet;55e6335f;NSArray
      { @selector( NSSet), @selector( NSCoder) },      // 9a5ad940;NSSet;57eb31d7;NSCoder
      { @selector( NSSet), @selector( NSMutableSet) },      // 9a5ad940;NSSet;e6cae1ee;NSMutableSet
      { @selector( NSSet), MULLE_OBJC_NO_CATEGORYID },      // 9a5ad940;NSSet;;
      { @selector( NSSortDescriptor), @selector( NSCoder) },      // 115836cf;NSSortDescriptor;57eb31d7;NSCoder
      { @selector( NSSortDescriptor), MULLE_OBJC_NO_CATEGORYID },      // 115836cf;NSSortDescriptor;;
      { @selector( NSString), @selector( ClassCluster) },      // 85e3fa43;NSString;9fe7683b;ClassCluster
      { @selector( NSString), @selector( Components) },      // 85e3fa43;NSString;4dd10b69;Components
      { @selector( NSString), @selector( Escaping) },      // 85e3fa43;NSString;9b2b4859;Escaping
      { @selector( NSString), @selector( Locale) },      // 85e3fa43;NSString;8b50377b;Locale
      { @selector( NSString), @selector( NSCharacterSet) },      // 85e3fa43;NSString;b452f5f7;NSCharacterSet
      { @selector( NSString), @selector( NSCoder) },      // 85e3fa43;NSString;57eb31d7;NSCoder
      { @selector( NSString), @selector( NSData) },      // 85e3fa43;NSString;7d1455e8;NSData
      { @selector( NSString), @selector( NSMutableString) },      // 85e3fa43;NSString;fcaa2a91;NSMutableString
      { @selector( NSString), @selector( NSPropertyListParsing) },      // 85e3fa43;NSString;d53dd685;NSPropertyListParsing
      { @selector( NSString), @selector( NSSearch) },      // 85e3fa43;NSString;47c61184;NSSearch
      { @selector( NSString), @selector( PropertyListPrinting) },      // 85e3fa43;NSString;1cb22f11;PropertyListPrinting
      { @selector( NSString), @selector( Sprintf) },      // 85e3fa43;NSString;af844695;Sprintf
      { @selector( NSString), MULLE_OBJC_NO_CATEGORYID },      // 85e3fa43;NSString;;
      { @selector( NSThread), @selector( NSDate) },      // 645eeb40;NSThread;7d1455ec;NSDate
      { @selector( NSThread), @selector( NSDictionary) },      // 645eeb40;NSThread;ca46313c;NSDictionary
      { @selector( NSThread), @selector( NSNotification) },      // 645eeb40;NSThread;18e88d95;NSNotification
      { @selector( NSTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 4bf7bd11;NSTimeZone;;
      { @selector( NSUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // bc40ee49;NSUnarchiver;;
      { @selector( NSValue), @selector( NSCoder) },      // b732699b;NSValue;57eb31d7;NSCoder
      { @selector( NSValue), @selector( NSString) },      // b732699b;NSValue;85e3fa43;NSString
      { @selector( NSValue), MULLE_OBJC_NO_CATEGORYID },      // b732699b;NSValue;;
      { @selector( _MulleObjCASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b17891ed;_MulleObjCASCIIString;;
      { @selector( _MulleObjCAllocatorASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b3b1aa1a;_MulleObjCAllocatorASCIIString;;
      { @selector( _MulleObjCAllocatorData), MULLE_OBJC_NO_CATEGORYID },      // 663063e8;_MulleObjCAllocatorData;;
      { @selector( _MulleObjCAllocatorUTF16String), MULLE_OBJC_NO_CATEGORYID },      // c3a3ab65;_MulleObjCAllocatorUTF16String;;
      { @selector( _MulleObjCAllocatorUTF32String), MULLE_OBJC_NO_CATEGORYID },      // a256bdf3;_MulleObjCAllocatorUTF32String;;
      { @selector( _MulleObjCArrayEnumerator), MULLE_OBJC_NO_CATEGORYID },      // d143a2c2;_MulleObjCArrayEnumerator;;
      { @selector( _MulleObjCBufferedDataInputStream), MULLE_OBJC_NO_CATEGORYID },      // 0d571f10;_MulleObjCBufferedDataInputStream;;
      { @selector( _MulleObjCBufferedDataOutputStream), MULLE_OBJC_NO_CATEGORYID },      // ef16bfd3;_MulleObjCBufferedDataOutputStream;;
      { @selector( _MulleObjCCheatingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 93c7de3c;_MulleObjCCheatingASCIIString;;
      { @selector( _MulleObjCConcreteArray), @selector( NSCoder) },      // 429b8f4b;_MulleObjCConcreteArray;57eb31d7;NSCoder
      { @selector( _MulleObjCConcreteArray), MULLE_OBJC_NO_CATEGORYID },      // 429b8f4b;_MulleObjCConcreteArray;;
      { @selector( _MulleObjCConcreteBitmapCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // b0c16d52;_MulleObjCConcreteBitmapCharacterSet;;
      { @selector( _MulleObjCConcreteCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 7a6cbb3b;_MulleObjCConcreteCharacterSet;;
      { @selector( _MulleObjCConcreteData), MULLE_OBJC_NO_CATEGORYID },      // 1f717c6c;_MulleObjCConcreteData;;
      { @selector( _MulleObjCConcreteDictionary), MULLE_OBJC_NO_CATEGORYID },      // 994b8bd0;_MulleObjCConcreteDictionary;;
      { @selector( _MulleObjCConcreteMutableData), MULLE_OBJC_NO_CATEGORYID },      // 07ff08b2;_MulleObjCConcreteMutableData;;
      { @selector( _MulleObjCConcreteMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 12b624de;_MulleObjCConcreteMutableDictionary;;
      { @selector( _MulleObjCConcreteMutableSet), MULLE_OBJC_NO_CATEGORYID },      // b136229a;_MulleObjCConcreteMutableSet;;
      { @selector( _MulleObjCConcreteRangeCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 40b6b334;_MulleObjCConcreteRangeCharacterSet;;
      { @selector( _MulleObjCConcreteSet), MULLE_OBJC_NO_CATEGORYID },      // 9b80027c;_MulleObjCConcreteSet;;
      { @selector( _MulleObjCConcreteValue), @selector( NSCoder) },      // f6981437;_MulleObjCConcreteValue;57eb31d7;NSCoder
      { @selector( _MulleObjCConcreteValue), MULLE_OBJC_NO_CATEGORYID },      // f6981437;_MulleObjCConcreteValue;;
      { @selector( _MulleObjCDictionary), MULLE_OBJC_NO_CATEGORYID },      // 5c32cfb5;_MulleObjCDictionary;;
      { @selector( _MulleObjCDictionaryKeyEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 349fca60;_MulleObjCDictionaryKeyEnumerator;;
      { @selector( _MulleObjCDictionaryObjectEnumerator), MULLE_OBJC_NO_CATEGORYID },      // ba82797a;_MulleObjCDictionaryObjectEnumerator;;
      { @selector( _MulleObjCDoubleNumber), @selector( NSString) },      // dc33cb0d;_MulleObjCDoubleNumber;85e3fa43;NSString
      { @selector( _MulleObjCDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // dc33cb0d;_MulleObjCDoubleNumber;;
      { @selector( _MulleObjCEightBytesData), MULLE_OBJC_NO_CATEGORYID },      // 4268aeab;_MulleObjCEightBytesData;;
      { @selector( _MulleObjCEmptyArray), MULLE_OBJC_NO_CATEGORYID },      // dc15d003;_MulleObjCEmptyArray;;
      { @selector( _MulleObjCEmptySet), MULLE_OBJC_NO_CATEGORYID },      // 0b68bf04;_MulleObjCEmptySet;;
      { @selector( _MulleObjCGenericASCIIString), MULLE_OBJC_NO_CATEGORYID },      // ae0c6852;_MulleObjCGenericASCIIString;;
      { @selector( _MulleObjCGenericUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 0b4cae5d;_MulleObjCGenericUTF16String;;
      { @selector( _MulleObjCGenericUTF32String), MULLE_OBJC_NO_CATEGORYID },      // dc84ee6b;_MulleObjCGenericUTF32String;;
      { @selector( _MulleObjCInt16Number), MULLE_OBJC_NO_CATEGORYID },      // 6fca9882;_MulleObjCInt16Number;;
      { @selector( _MulleObjCInt32Number), MULLE_OBJC_NO_CATEGORYID },      // c4c92a2c;_MulleObjCInt32Number;;
      { @selector( _MulleObjCInt64Number), MULLE_OBJC_NO_CATEGORYID },      // e3f49f9d;_MulleObjCInt64Number;;
      { @selector( _MulleObjCInt8Number), MULLE_OBJC_NO_CATEGORYID },      // d674370b;_MulleObjCInt8Number;;
      { @selector( _MulleObjCLocalTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 9b685e8f;_MulleObjCLocalTimeZone;;
      { @selector( _MulleObjCLongDoubleNumber), @selector( NSString) },      // 82e6ea4f;_MulleObjCLongDoubleNumber;85e3fa43;NSString
      { @selector( _MulleObjCLongDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 82e6ea4f;_MulleObjCLongDoubleNumber;;
      { @selector( _MulleObjCMediumData), MULLE_OBJC_NO_CATEGORYID },      // 850699c0;_MulleObjCMediumData;;
      { @selector( _MulleObjCMemoryDataInputStream), MULLE_OBJC_NO_CATEGORYID },      // a2abd19c;_MulleObjCMemoryDataInputStream;;
      { @selector( _MulleObjCPropertyListReader), MULLE_OBJC_NO_CATEGORYID },      // 5f6f56ff;_MulleObjCPropertyListReader;;
      { @selector( _MulleObjCReferencingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 62ac41ad;_MulleObjCReferencingASCIIString;;
      { @selector( _MulleObjCSet), MULLE_OBJC_NO_CATEGORYID },      // 6c4a19bf;_MulleObjCSet;;
      { @selector( _MulleObjCSetEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 41aabe4d;_MulleObjCSetEnumerator;;
      { @selector( _MulleObjCSharedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 39568c40;_MulleObjCSharedASCIIString;;
      { @selector( _MulleObjCSharedData), MULLE_OBJC_NO_CATEGORYID },      // f173b26a;_MulleObjCSharedData;;
      { @selector( _MulleObjCSharedUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 5125ac3b;_MulleObjCSharedUTF16String;;
      { @selector( _MulleObjCSharedUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 8c5cdcb5;_MulleObjCSharedUTF32String;;
      { @selector( _MulleObjCSixteenBytesData), MULLE_OBJC_NO_CATEGORYID },      // d1d33ea0;_MulleObjCSixteenBytesData;;
      { @selector( _MulleObjCTaggedPointerChar5String), MULLE_OBJC_NO_CATEGORYID },      // e5265a16;_MulleObjCTaggedPointerChar5String;;
      { @selector( _MulleObjCTaggedPointerChar7String), MULLE_OBJC_NO_CATEGORYID },      // 5c2b0d90;_MulleObjCTaggedPointerChar7String;;
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSCoder) },      // 7505d5b1;_MulleObjCTaggedPointerIntegerNumber;57eb31d7;NSCoder
      { @selector( _MulleObjCTaggedPointerIntegerNumber), MULLE_OBJC_NO_CATEGORYID },      // 7505d5b1;_MulleObjCTaggedPointerIntegerNumber;;
      { @selector( _MulleObjCTinyASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 187c1c2f;_MulleObjCTinyASCIIString;;
      { @selector( _MulleObjCTinyData), MULLE_OBJC_NO_CATEGORYID },      // 10a5f233;_MulleObjCTinyData;;
      { @selector( _MulleObjCUInt32Number), @selector( NSString) },      // 4876770d;_MulleObjCUInt32Number;85e3fa43;NSString
      { @selector( _MulleObjCUInt32Number), MULLE_OBJC_NO_CATEGORYID },      // 4876770d;_MulleObjCUInt32Number;;
      { @selector( _MulleObjCUInt64Number), @selector( NSString) },      // c9a449b0;_MulleObjCUInt64Number;85e3fa43;NSString
      { @selector( _MulleObjCUInt64Number), MULLE_OBJC_NO_CATEGORYID },      // c9a449b0;_MulleObjCUInt64Number;;
      { @selector( _MulleObjCUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 59aea06e;_MulleObjCUTF16String;;
      { @selector( _MulleObjCUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 8125da64;_MulleObjCUTF32String;;
      { @selector( _MulleObjCUTF8StreamReader), MULLE_OBJC_NO_CATEGORYID },      // 019bce09;_MulleObjCUTF8StreamReader;;
      { @selector( _MulleObjCZeroBytesData), MULLE_OBJC_NO_CATEGORYID },      // bce2b0c8;_MulleObjCZeroBytesData;;
      { @selector( _NSGMTTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 50cec3ce;_NSGMTTimeZone;;
