      { @selector( MulleObjCArchiver), MULLE_OBJC_NO_CATEGORYID },      // 6c636b4d;MulleObjCArchiver;;
      { @selector( MulleObjCArrayReverseEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 1f04617c;MulleObjCArrayReverseEnumerator;;
      { @selector( MulleObjCUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 6c32efb0;MulleObjCUnarchiver;;
      { @selector( MulleObjCUnkeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // f57df630;MulleObjCUnkeyedArchiver;;
      { @selector( MulleObjCUnkeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 2b124a0f;MulleObjCUnkeyedUnarchiver;;
      { @selector( NSArchiver), MULLE_OBJC_NO_CATEGORYID },      // 2a2e712f;NSArchiver;;
      { @selector( NSArray), @selector( NSCoder) },      // 233490fe;NSArray;100c54ba;NSCoder
      { @selector( NSArray), @selector( NSLocale) },      // 233490fe;NSArray;22b7d78c;NSLocale
      { @selector( NSArray), @selector( NSMutableCopying) },      // 233490fe;NSArray;4aa86031;NSMutableCopying
      { @selector( NSArray), @selector( NSPropertyListParsing) },      // 233490fe;NSArray;060a8c9c;NSPropertyListParsing
      { @selector( NSArray), @selector( NSSortDescriptor) },      // 233490fe;NSArray;38a79ab2;NSSortDescriptor
      { @selector( NSArray), @selector( NSString) },      // 233490fe;NSArray;1994a171;NSString
      { @selector( NSArray), @selector( PropertyListPrinting) },      // 233490fe;NSArray;91aeee11;PropertyListPrinting
      { @selector( NSArray), MULLE_OBJC_NO_CATEGORYID },      // 233490fe;NSArray;;
      { @selector( NSAssertionHandler), MULLE_OBJC_NO_CATEGORYID },      // a1951b2b;NSAssertionHandler;;
      { @selector( NSCalendarDate), @selector( NSDateFormatter) },      // b8742fcb;NSCalendarDate;6d2cd542;NSDateFormatter
      { @selector( NSCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // b8742fcb;NSCalendarDate;;
      { @selector( NSCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // bb258d72;NSCharacterSet;;
      { @selector( NSCoder), MULLE_OBJC_NO_CATEGORYID },      // 100c54ba;NSCoder;;
      { @selector( NSConstantString), MULLE_OBJC_NO_CATEGORYID },      // 02cf74f7;NSConstantString;;
      { @selector( NSData), @selector( NSCoder) },      // 8fce7861;NSData;100c54ba;NSCoder
      { @selector( NSData), @selector( NSMutableCopying) },      // 8fce7861;NSData;4aa86031;NSMutableCopying
      { @selector( NSData), @selector( NSPropertyListParsing) },      // 8fce7861;NSData;060a8c9c;NSPropertyListParsing
      { @selector( NSData), @selector( NSString) },      // 8fce7861;NSData;1994a171;NSString
      { @selector( NSData), @selector( PropertyListPrinting) },      // 8fce7861;NSData;91aeee11;PropertyListPrinting
      { @selector( NSData), @selector( _Unicode) },      // 8fce7861;NSData;ac921392;_Unicode
      { @selector( NSData), MULLE_OBJC_NO_CATEGORYID },      // 8fce7861;NSData;;
      { @selector( NSDate), @selector( NSCalendarDate) },      // cfcedd21;NSDate;b8742fcb;NSCalendarDate
      { @selector( NSDate), @selector( NSCoder) },      // cfcedd21;NSDate;100c54ba;NSCoder
      { @selector( NSDate), @selector( NSDateFormatter) },      // cfcedd21;NSDate;6d2cd542;NSDateFormatter
      { @selector( NSDate), @selector( PropertyListPrinting) },      // cfcedd21;NSDate;91aeee11;PropertyListPrinting
      { @selector( NSDate), MULLE_OBJC_NO_CATEGORYID },      // cfcedd21;NSDate;;
      { @selector( NSDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // 6d2cd542;NSDateFormatter;;
      { @selector( NSDictionary), @selector( NSArray) },      // 8b2abcad;NSDictionary;233490fe;NSArray
      { @selector( NSDictionary), @selector( NSCoder) },      // 8b2abcad;NSDictionary;100c54ba;NSCoder
      { @selector( NSDictionary), @selector( NSLocale) },      // 8b2abcad;NSDictionary;22b7d78c;NSLocale
      { @selector( NSDictionary), @selector( NSMutableDictionary) },      // 8b2abcad;NSDictionary;2f2fa84a;NSMutableDictionary
      { @selector( NSDictionary), @selector( NSPropertyListParsing) },      // 8b2abcad;NSDictionary;060a8c9c;NSPropertyListParsing
      { @selector( NSDictionary), @selector( NSString) },      // 8b2abcad;NSDictionary;1994a171;NSString
      { @selector( NSDictionary), @selector( PropertyListPrinting) },      // 8b2abcad;NSDictionary;91aeee11;PropertyListPrinting
      { @selector( NSDictionary), MULLE_OBJC_NO_CATEGORYID },      // 8b2abcad;NSDictionary;;
      { @selector( NSEnumerator), @selector( NSArray) },      // e631d30d;NSEnumerator;233490fe;NSArray
      { @selector( NSEnumerator), @selector( Perform) },      // e631d30d;NSEnumerator;836b3627;Perform
      { @selector( NSEnumerator), MULLE_OBJC_NO_CATEGORYID },      // e631d30d;NSEnumerator;;
      { @selector( NSError), MULLE_OBJC_NO_CATEGORYID },      // 17836f0e;NSError;;
      { @selector( NSException), @selector( String) },      // 332ec6f9;NSException;04f48586;String
      { @selector( NSException), MULLE_OBJC_NO_CATEGORYID },      // 332ec6f9;NSException;;
      { @selector( NSFormatter), MULLE_OBJC_NO_CATEGORYID },      // d5e6770e;NSFormatter;;
      { @selector( NSKeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 8a2c6980;NSKeyedArchiver;;
      { @selector( NSKeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // ea42e9ff;NSKeyedUnarchiver;;
      { @selector( NSLocale), MULLE_OBJC_NO_CATEGORYID },      // 22b7d78c;NSLocale;;
      { @selector( NSLock), @selector( NSDate) },      // cd92d31f;NSLock;cfcedd21;NSDate
      { @selector( NSMethodSignature), @selector( NSString) },      // 523989f9;NSMethodSignature;1994a171;NSString
      { @selector( NSMutableArray), @selector( NSCoder) },      // f5e6dbdd;NSMutableArray;100c54ba;NSCoder
      { @selector( NSMutableArray), @selector( NSSortDescriptor) },      // f5e6dbdd;NSMutableArray;38a79ab2;NSSortDescriptor
      { @selector( NSMutableArray), MULLE_OBJC_NO_CATEGORYID },      // f5e6dbdd;NSMutableArray;;
      { @selector( NSMutableData), @selector( NSCoder) },      // 5d7fdc81;NSMutableData;100c54ba;NSCoder
      { @selector( NSMutableData), @selector( _MulleObjCOutputDataStream) },      // 5d7fdc81;NSMutableData;2ac26786;_MulleObjCOutputDataStream
      { @selector( NSMutableData), MULLE_OBJC_NO_CATEGORYID },      // 5d7fdc81;NSMutableData;;
      { @selector( NSMutableDictionary), @selector( NSArray) },      // 2f2fa84a;NSMutableDictionary;233490fe;NSArray
      { @selector( NSMutableDictionary), @selector( NSCoder) },      // 2f2fa84a;NSMutableDictionary;100c54ba;NSCoder
      { @selector( NSMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2f2fa84a;NSMutableDictionary;;
      { @selector( NSMutableSet), @selector( NSArray) },      // 1fa72100;NSMutableSet;233490fe;NSArray
      { @selector( NSMutableSet), @selector( NSCoder) },      // 1fa72100;NSMutableSet;100c54ba;NSCoder
      { @selector( NSMutableSet), MULLE_OBJC_NO_CATEGORYID },      // 1fa72100;NSMutableSet;;
      { @selector( NSMutableString), @selector( NSData) },      // 63662493;NSMutableString;8fce7861;NSData
      { @selector( NSMutableString), MULLE_OBJC_NO_CATEGORYID },      // 63662493;NSMutableString;;
      { @selector( NSNotification), MULLE_OBJC_NO_CATEGORYID },      // 4cf6fadb;NSNotification;;
      { @selector( NSNotificationCenter), MULLE_OBJC_NO_CATEGORYID },      // 1c4865c0;NSNotificationCenter;;
      { @selector( NSNull), MULLE_OBJC_NO_CATEGORYID },      // f0c42d79;NSNull;;
      { @selector( NSNumber), @selector( NSCoder) },      // 8ba34f39;NSNumber;100c54ba;NSCoder
      { @selector( NSNumber), @selector( NSLocale) },      // 8ba34f39;NSNumber;22b7d78c;NSLocale
      { @selector( NSNumber), @selector( NSString) },      // 8ba34f39;NSNumber;1994a171;NSString
      { @selector( NSNumber), @selector( PropertyListPrinting) },      // 8ba34f39;NSNumber;91aeee11;PropertyListPrinting
      { @selector( NSNumber), MULLE_OBJC_NO_CATEGORYID },      // 8ba34f39;NSNumber;;
      { @selector( NSNumberFormatter), MULLE_OBJC_NO_CATEGORYID },      // 60a672fc;NSNumberFormatter;;
      { @selector( NSObject), @selector( NSCoder) },      // b3a66256;NSObject;100c54ba;NSCoder
      { @selector( NSObject), @selector( NSPropertyListParsing) },      // b3a66256;NSObject;060a8c9c;NSPropertyListParsing
      { @selector( NSObject), @selector( NSString) },      // b3a66256;NSObject;1994a171;NSString
      { @selector( NSObject), @selector( PropertyListPrinting) },      // b3a66256;NSObject;91aeee11;PropertyListPrinting
      { @selector( NSObject), @selector( _NSArray) },      // b3a66256;NSObject;0beba328;_NSArray
      { @selector( NSObject), @selector( _NSCalendarDate) },      // b3a66256;NSObject;83e2187c;_NSCalendarDate
      { @selector( NSObject), @selector( _NSData) },      // b3a66256;NSObject;7f24339e;_NSData
      { @selector( NSObject), @selector( _NSDate) },      // b3a66256;NSObject;bf24985e;_NSDate
      { @selector( NSObject), @selector( _NSDictionary) },      // b3a66256;NSObject;413cd390;_NSDictionary
      { @selector( NSObject), @selector( _NSLocale) },      // b3a66256;NSObject;973379b2;_NSLocale
      { @selector( NSObject), @selector( _NSMutableData) },      // b3a66256;NSObject;1a3fbdd6;_NSMutableData
      { @selector( NSObject), @selector( _NSMutableDictionary) },      // b3a66256;NSObject;1f96dfdd;_NSMutableDictionary
      { @selector( NSObject), @selector( _NSMutableString) },      // b3a66256;NSObject;7bd64f0d;_NSMutableString
      { @selector( NSObject), @selector( _NSNull) },      // b3a66256;NSObject;90d3fc87;_NSNull
      { @selector( NSObject), @selector( _NSNumber) },      // b3a66256;NSObject;9343014d;_NSNumber
      { @selector( NSObject), @selector( _NSSet) },      // b3a66256;NSObject;2f766bf1;_NSSet
      { @selector( NSObject), @selector( _NSString) },      // b3a66256;NSObject;37e49041;_NSString
      { @selector( NSObject), @selector( _NSTimeZone) },      // b3a66256;NSObject;f3165c68;_NSTimeZone
      { @selector( NSObject), @selector( _NSValue) },      // b3a66256;NSObject;8fc3f568;_NSValue
      { @selector( NSPropertyListSerialization), MULLE_OBJC_NO_CATEGORYID },      // 87901b51;NSPropertyListSerialization;;
      { @selector( NSScanner), MULLE_OBJC_NO_CATEGORYID },      // 0b3d6aca;NSScanner;;
      { @selector( NSSet), @selector( NSArray) },      // 9f69e3e4;NSSet;233490fe;NSArray
      { @selector( NSSet), @selector( NSCoder) },      // 9f69e3e4;NSSet;100c54ba;NSCoder
      { @selector( NSSet), @selector( NSMutableSet) },      // 9f69e3e4;NSSet;1fa72100;NSMutableSet
      { @selector( NSSet), MULLE_OBJC_NO_CATEGORYID },      // 9f69e3e4;NSSet;;
      { @selector( NSSortDescriptor), @selector( NSCoder) },      // 38a79ab2;NSSortDescriptor;100c54ba;NSCoder
      { @selector( NSSortDescriptor), MULLE_OBJC_NO_CATEGORYID },      // 38a79ab2;NSSortDescriptor;;
      { @selector( NSString), @selector( ClassCluster) },      // 1994a171;NSString;d38b16ff;ClassCluster
      { @selector( NSString), @selector( Components) },      // 1994a171;NSString;c6c03895;Components
      { @selector( NSString), @selector( Escaping) },      // 1994a171;NSString;742c5512;Escaping
      { @selector( NSString), @selector( Locale) },      // 1994a171;NSString;d6e5bb7d;Locale
      { @selector( NSString), @selector( NSCharacterSet) },      // 1994a171;NSString;bb258d72;NSCharacterSet
      { @selector( NSString), @selector( NSCoder) },      // 1994a171;NSString;100c54ba;NSCoder
      { @selector( NSString), @selector( NSData) },      // 1994a171;NSString;8fce7861;NSData
      { @selector( NSString), @selector( NSMutableString) },      // 1994a171;NSString;63662493;NSMutableString
      { @selector( NSString), @selector( NSPropertyListParsing) },      // 1994a171;NSString;060a8c9c;NSPropertyListParsing
      { @selector( NSString), @selector( NSSearch) },      // 1994a171;NSString;cee9d062;NSSearch
      { @selector( NSString), @selector( PropertyListPrinting) },      // 1994a171;NSString;91aeee11;PropertyListPrinting
      { @selector( NSString), @selector( Sprintf) },      // 1994a171;NSString;8d371e94;Sprintf
      { @selector( NSString), MULLE_OBJC_NO_CATEGORYID },      // 1994a171;NSString;;
      { @selector( NSThread), @selector( NSDate) },      // c81b9c22;NSThread;cfcedd21;NSDate
      { @selector( NSThread), @selector( NSDictionary) },      // c81b9c22;NSThread;8b2abcad;NSDictionary
      { @selector( NSThread), @selector( NSNotification) },      // c81b9c22;NSThread;4cf6fadb;NSNotification
      { @selector( NSTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 190d1ade;NSTimeZone;;
      { @selector( NSUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 2b47ff54;NSUnarchiver;;
      { @selector( NSValue), @selector( NSCoder) },      // 96deaa7d;NSValue;100c54ba;NSCoder
      { @selector( NSValue), @selector( NSString) },      // 96deaa7d;NSValue;1994a171;NSString
      { @selector( NSValue), MULLE_OBJC_NO_CATEGORYID },      // 96deaa7d;NSValue;;
      { @selector( _MulleObjCASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b82142dd;_MulleObjCASCIIString;;
      { @selector( _MulleObjCAllocatorASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b8b17987;_MulleObjCAllocatorASCIIString;;
      { @selector( _MulleObjCAllocatorData), MULLE_OBJC_NO_CATEGORYID },      // 888d9e62;_MulleObjCAllocatorData;;
      { @selector( _MulleObjCAllocatorUTF16String), MULLE_OBJC_NO_CATEGORYID },      // fadd0998;_MulleObjCAllocatorUTF16String;;
      { @selector( _MulleObjCAllocatorUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 22d56278;_MulleObjCAllocatorUTF32String;;
      { @selector( _MulleObjCArrayEnumerator), MULLE_OBJC_NO_CATEGORYID },      // b826ca4d;_MulleObjCArrayEnumerator;;
      { @selector( _MulleObjCBufferedDataInputStream), MULLE_OBJC_NO_CATEGORYID },      // 581653a8;_MulleObjCBufferedDataInputStream;;
      { @selector( _MulleObjCBufferedDataOutputStream), MULLE_OBJC_NO_CATEGORYID },      // a251e479;_MulleObjCBufferedDataOutputStream;;
      { @selector( _MulleObjCCheatingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // c16079ee;_MulleObjCCheatingASCIIString;;
      { @selector( _MulleObjCConcreteArray), @selector( NSCoder) },      // 3610e4bd;_MulleObjCConcreteArray;100c54ba;NSCoder
      { @selector( _MulleObjCConcreteArray), MULLE_OBJC_NO_CATEGORYID },      // 3610e4bd;_MulleObjCConcreteArray;;
      { @selector( _MulleObjCConcreteBitmapCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 0846adc2;_MulleObjCConcreteBitmapCharacterSet;;
      { @selector( _MulleObjCConcreteCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // ba1004b2;_MulleObjCConcreteCharacterSet;;
      { @selector( _MulleObjCConcreteData), MULLE_OBJC_NO_CATEGORYID },      // 9971ffa3;_MulleObjCConcreteData;;
      { @selector( _MulleObjCConcreteDictionary), MULLE_OBJC_NO_CATEGORYID },      // aa37b8ec;_MulleObjCConcreteDictionary;;
      { @selector( _MulleObjCConcreteMutableData), MULLE_OBJC_NO_CATEGORYID },      // 55d549c0;_MulleObjCConcreteMutableData;;
      { @selector( _MulleObjCConcreteMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2ce9638f;_MulleObjCConcreteMutableDictionary;;
      { @selector( _MulleObjCConcreteMutableSet), MULLE_OBJC_NO_CATEGORYID },      // b7eb37c0;_MulleObjCConcreteMutableSet;;
      { @selector( _MulleObjCConcreteRangeCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 09c86c6e;_MulleObjCConcreteRangeCharacterSet;;
      { @selector( _MulleObjCConcreteSet), MULLE_OBJC_NO_CATEGORYID },      // 2823d0a0;_MulleObjCConcreteSet;;
      { @selector( _MulleObjCConcreteValue), @selector( NSCoder) },      // 7aa5a738;_MulleObjCConcreteValue;100c54ba;NSCoder
      { @selector( _MulleObjCConcreteValue), MULLE_OBJC_NO_CATEGORYID },      // 7aa5a738;_MulleObjCConcreteValue;;
      { @selector( _MulleObjCDictionary), MULLE_OBJC_NO_CATEGORYID },      // 2b722f90;_MulleObjCDictionary;;
      { @selector( _MulleObjCDictionaryKeyEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 047702a5;_MulleObjCDictionaryKeyEnumerator;;
      { @selector( _MulleObjCDictionaryObjectEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 49965c09;_MulleObjCDictionaryObjectEnumerator;;
      { @selector( _MulleObjCDoubleNumber), @selector( NSString) },      // ae25b758;_MulleObjCDoubleNumber;1994a171;NSString
      { @selector( _MulleObjCDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // ae25b758;_MulleObjCDoubleNumber;;
      { @selector( _MulleObjCEightBytesData), MULLE_OBJC_NO_CATEGORYID },      // 7ac60bf2;_MulleObjCEightBytesData;;
      { @selector( _MulleObjCEmptyArray), MULLE_OBJC_NO_CATEGORYID },      // 7aa0d636;_MulleObjCEmptyArray;;
      { @selector( _MulleObjCEmptySet), MULLE_OBJC_NO_CATEGORYID },      // b4c55b26;_MulleObjCEmptySet;;
      { @selector( _MulleObjCGenericASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 2c4a2683;_MulleObjCGenericASCIIString;;
      { @selector( _MulleObjCGenericUTF16String), MULLE_OBJC_NO_CATEGORYID },      // ceb45c9e;_MulleObjCGenericUTF16String;;
      { @selector( _MulleObjCGenericUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 57fe0d78;_MulleObjCGenericUTF32String;;
      { @selector( _MulleObjCInt16Number), MULLE_OBJC_NO_CATEGORYID },      // 8992560e;_MulleObjCInt16Number;;
      { @selector( _MulleObjCInt32Number), MULLE_OBJC_NO_CATEGORYID },      // d69971a0;_MulleObjCInt32Number;;
      { @selector( _MulleObjCInt64Number), MULLE_OBJC_NO_CATEGORYID },      // 8b4d5e19;_MulleObjCInt64Number;;
      { @selector( _MulleObjCInt8Number), MULLE_OBJC_NO_CATEGORYID },      // 9cff1f3f;_MulleObjCInt8Number;;
      { @selector( _MulleObjCLocalTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 5813d6fc;_MulleObjCLocalTimeZone;;
      { @selector( _MulleObjCLongDoubleNumber), @selector( NSString) },      // 4ec38072;_MulleObjCLongDoubleNumber;1994a171;NSString
      { @selector( _MulleObjCLongDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 4ec38072;_MulleObjCLongDoubleNumber;;
      { @selector( _MulleObjCMediumData), MULLE_OBJC_NO_CATEGORYID },      // bcd94429;_MulleObjCMediumData;;
      { @selector( _MulleObjCMemoryDataInputStream), MULLE_OBJC_NO_CATEGORYID },      // 0a00da66;_MulleObjCMemoryDataInputStream;;
      { @selector( _MulleObjCPropertyListReader), MULLE_OBJC_NO_CATEGORYID },      // a2dc8d79;_MulleObjCPropertyListReader;;
      { @selector( _MulleObjCReferencingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b6861455;_MulleObjCReferencingASCIIString;;
      { @selector( _MulleObjCSet), MULLE_OBJC_NO_CATEGORYID },      // 5da537fa;_MulleObjCSet;;
      { @selector( _MulleObjCSetEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 832b431a;_MulleObjCSetEnumerator;;
      { @selector( _MulleObjCSharedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a4a89e62;_MulleObjCSharedASCIIString;;
      { @selector( _MulleObjCSharedData), MULLE_OBJC_NO_CATEGORYID },      // 71db1e02;_MulleObjCSharedData;;
      { @selector( _MulleObjCSharedUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 06c03572;_MulleObjCSharedUTF16String;;
      { @selector( _MulleObjCSharedUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 6762de13;_MulleObjCSharedUTF32String;;
      { @selector( _MulleObjCSixteenBytesData), MULLE_OBJC_NO_CATEGORYID },      // 4b47402e;_MulleObjCSixteenBytesData;;
      { @selector( _MulleObjCTaggedPointerChar5String), MULLE_OBJC_NO_CATEGORYID },      // 2a6d1009;_MulleObjCTaggedPointerChar5String;;
      { @selector( _MulleObjCTaggedPointerChar7String), MULLE_OBJC_NO_CATEGORYID },      // d68ecb24;_MulleObjCTaggedPointerChar7String;;
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSCoder) },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;100c54ba;NSCoder
      { @selector( _MulleObjCTaggedPointerIntegerNumber), MULLE_OBJC_NO_CATEGORYID },      // 1f557819;_MulleObjCTaggedPointerIntegerNumber;;
      { @selector( _MulleObjCTinyASCIIString), MULLE_OBJC_NO_CATEGORYID },      // a20ee3f6;_MulleObjCTinyASCIIString;;
      { @selector( _MulleObjCTinyData), MULLE_OBJC_NO_CATEGORYID },      // ed2fbb7a;_MulleObjCTinyData;;
      { @selector( _MulleObjCUInt32Number), @selector( NSString) },      // 92030c9c;_MulleObjCUInt32Number;1994a171;NSString
      { @selector( _MulleObjCUInt32Number), MULLE_OBJC_NO_CATEGORYID },      // 92030c9c;_MulleObjCUInt32Number;;
      { @selector( _MulleObjCUInt64Number), @selector( NSString) },      // c62e3ae1;_MulleObjCUInt64Number;1994a171;NSString
      { @selector( _MulleObjCUInt64Number), MULLE_OBJC_NO_CATEGORYID },      // c62e3ae1;_MulleObjCUInt64Number;;
      { @selector( _MulleObjCUTF16String), MULLE_OBJC_NO_CATEGORYID },      // d817650f;_MulleObjCUTF16String;;
      { @selector( _MulleObjCUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 318d8f60;_MulleObjCUTF32String;;
      { @selector( _MulleObjCUTF8StreamReader), MULLE_OBJC_NO_CATEGORYID },      // cbcbf81e;_MulleObjCUTF8StreamReader;;
      { @selector( _MulleObjCZeroBytesData), MULLE_OBJC_NO_CATEGORYID },      // e3b0c32a;_MulleObjCZeroBytesData;;
      { @selector( _NSGMTTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 60527041;_NSGMTTimeZone;;
