      { @selector( MulleObjCArchiver), MULLE_OBJC_NO_CATEGORYID },      // dbbd06ce,00000000
      { @selector( MulleObjCArrayReverseEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 4e90599f,00000000
      { @selector( MulleObjCUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 6a4e784f,00000000
      { @selector( MulleObjCUnkeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 6651b187,00000000
      { @selector( MulleObjCUnkeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // 1192b722,00000000
      { @selector( NSArchiver), MULLE_OBJC_NO_CATEGORYID },      // 3140e86c,00000000
      { @selector( NSArray), @selector( NSCoder) },      // 55e6335f,57eb31d7
      { @selector( NSArray), @selector( NSLocale) },      // 55e6335f,60293bce
      { @selector( NSArray), @selector( NSMutableCopying) },      // 55e6335f,e5a2a39b
      { @selector( NSArray), @selector( NSPropertyListParsing) },      // 55e6335f,d53dd685
      { @selector( NSArray), @selector( NSSortDescriptor) },      // 55e6335f,115836cf
      { @selector( NSArray), @selector( NSString) },      // 55e6335f,85e3fa43
      { @selector( NSArray), @selector( PropertyListPrinting) },      // 55e6335f,1cb22f11
      { @selector( NSArray), MULLE_OBJC_NO_CATEGORYID },      // 55e6335f,00000000
      { @selector( NSAssertionHandler), MULLE_OBJC_NO_CATEGORYID },      // ae7c3830,00000000
      { @selector( NSCalendarDate), @selector( NSDateFormatter) },      // 732630c6,baad3d86
      { @selector( NSCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // 732630c6,00000000
      { @selector( NSCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // b452f5f7,00000000
      { @selector( NSCoder), MULLE_OBJC_NO_CATEGORYID },      // 57eb31d7,00000000
      { @selector( NSConstantString), MULLE_OBJC_NO_CATEGORYID },      // 83ca6a67,00000000
      { @selector( NSData), @selector( NSCoder) },      // 7d1455e8,57eb31d7
      { @selector( NSData), @selector( NSMutableCopying) },      // 7d1455e8,e5a2a39b
      { @selector( NSData), @selector( NSPropertyListParsing) },      // 7d1455e8,d53dd685
      { @selector( NSData), @selector( NSString) },      // 7d1455e8,85e3fa43
      { @selector( NSData), @selector( PropertyListPrinting) },      // 7d1455e8,1cb22f11
      { @selector( NSData), @selector( _Unicode) },      // 7d1455e8,b9067a61
      { @selector( NSData), MULLE_OBJC_NO_CATEGORYID },      // 7d1455e8,00000000
      { @selector( NSDate), @selector( NSCalendarDate) },      // 7d1455ec,732630c6
      { @selector( NSDate), @selector( NSCoder) },      // 7d1455ec,57eb31d7
      { @selector( NSDate), @selector( NSDateFormatter) },      // 7d1455ec,baad3d86
      { @selector( NSDate), @selector( PropertyListPrinting) },      // 7d1455ec,1cb22f11
      { @selector( NSDate), MULLE_OBJC_NO_CATEGORYID },      // 7d1455ec,00000000
      { @selector( NSDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // baad3d86,00000000
      { @selector( NSDictionary), @selector( NSArray) },      // ca46313c,55e6335f
      { @selector( NSDictionary), @selector( NSCoder) },      // ca46313c,57eb31d7
      { @selector( NSDictionary), @selector( NSLocale) },      // ca46313c,60293bce
      { @selector( NSDictionary), @selector( NSMutableDictionary) },      // ca46313c,edeb2f5a
      { @selector( NSDictionary), @selector( NSPropertyListParsing) },      // ca46313c,d53dd685
      { @selector( NSDictionary), @selector( NSString) },      // ca46313c,85e3fa43
      { @selector( NSDictionary), @selector( PropertyListPrinting) },      // ca46313c,1cb22f11
      { @selector( NSDictionary), MULLE_OBJC_NO_CATEGORYID },      // ca46313c,00000000
      { @selector( NSEnumerator), @selector( NSArray) },      // 3ff70b6e,55e6335f
      { @selector( NSEnumerator), @selector( Perform) },      // 3ff70b6e,d7dcdc48
      { @selector( NSEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 3ff70b6e,00000000
      { @selector( NSError), MULLE_OBJC_NO_CATEGORYID },      // d49f3e12,00000000
      { @selector( NSException), @selector( String) },      // a41284db,97be4a2e
      { @selector( NSException), MULLE_OBJC_NO_CATEGORYID },      // a41284db,00000000
      { @selector( NSFormatter), MULLE_OBJC_NO_CATEGORYID },      // 40625392,00000000
      { @selector( NSKeyedArchiver), MULLE_OBJC_NO_CATEGORYID },      // 028c2ebe,00000000
      { @selector( NSKeyedUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // e7d1c4df,00000000
      { @selector( NSLocale), MULLE_OBJC_NO_CATEGORYID },      // 60293bce,00000000
      { @selector( NSLock), @selector( NSDate) },      // ccba22ad,7d1455ec
      { @selector( NSMethodSignature), @selector( NSString) },      // 6901a863,85e3fa43
      { @selector( NSMutableArray), @selector( NSCoder) },      // 33fb2e49,57eb31d7
      { @selector( NSMutableArray), @selector( NSSortDescriptor) },      // 33fb2e49,115836cf
      { @selector( NSMutableArray), MULLE_OBJC_NO_CATEGORYID },      // 33fb2e49,00000000
      { @selector( NSMutableData), @selector( NSCoder) },      // 80af06be,57eb31d7
      { @selector( NSMutableData), @selector( _MulleObjCOutputDataStream) },      // 80af06be,a6b09746
      { @selector( NSMutableData), MULLE_OBJC_NO_CATEGORYID },      // 80af06be,00000000
      { @selector( NSMutableDictionary), @selector( NSArray) },      // edeb2f5a,55e6335f
      { @selector( NSMutableDictionary), @selector( NSCoder) },      // edeb2f5a,57eb31d7
      { @selector( NSMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // edeb2f5a,00000000
      { @selector( NSMutableSet), @selector( NSArray) },      // e6cae1ee,55e6335f
      { @selector( NSMutableSet), @selector( NSCoder) },      // e6cae1ee,57eb31d7
      { @selector( NSMutableSet), MULLE_OBJC_NO_CATEGORYID },      // e6cae1ee,00000000
      { @selector( NSMutableString), @selector( NSData) },      // fcaa2a91,7d1455e8
      { @selector( NSMutableString), MULLE_OBJC_NO_CATEGORYID },      // fcaa2a91,00000000
      { @selector( NSNotification), MULLE_OBJC_NO_CATEGORYID },      // 18e88d95,00000000
      { @selector( NSNotificationCenter), MULLE_OBJC_NO_CATEGORYID },      // 385d8f76,00000000
      { @selector( NSNull), MULLE_OBJC_NO_CATEGORYID },      // d33643ef,00000000
      { @selector( NSNumber), @selector( NSCoder) },      // 1fa441bb,57eb31d7
      { @selector( NSNumber), @selector( NSLocale) },      // 1fa441bb,60293bce
      { @selector( NSNumber), @selector( NSString) },      // 1fa441bb,85e3fa43
      { @selector( NSNumber), @selector( PropertyListPrinting) },      // 1fa441bb,1cb22f11
      { @selector( NSNumber), MULLE_OBJC_NO_CATEGORYID },      // 1fa441bb,00000000
      { @selector( NSNumberFormatter), MULLE_OBJC_NO_CATEGORYID },      // 883530b3,00000000
      { @selector( NSObject), @selector( NSCoder) },      // e9e78cbd,57eb31d7
      { @selector( NSObject), @selector( NSPropertyListParsing) },      // e9e78cbd,d53dd685
      { @selector( NSObject), @selector( NSString) },      // e9e78cbd,85e3fa43
      { @selector( NSObject), @selector( PropertyListPrinting) },      // e9e78cbd,1cb22f11
      { @selector( NSObject), @selector( _NSArray) },      // e9e78cbd,f49cb130
      { @selector( NSObject), @selector( _NSCalendarDate) },      // e9e78cbd,2eef2477
      { @selector( NSObject), @selector( _NSData) },      // e9e78cbd,fa6e9c31
      { @selector( NSObject), @selector( _NSDate) },      // e9e78cbd,fa6e9c35
      { @selector( NSObject), @selector( _NSDictionary) },      // e9e78cbd,5ecb4561
      { @selector( NSObject), @selector( _NSLocale) },      // e9e78cbd,776e7caf
      { @selector( NSObject), @selector( _NSMutableData) },      // e9e78cbd,bafcf24d
      { @selector( NSObject), @selector( _NSMutableDictionary) },      // e9e78cbd,d788570d
      { @selector( NSObject), @selector( _NSMutableString) },      // e9e78cbd,a2572c1e
      { @selector( NSObject), @selector( _NSNull) },      // e9e78cbd,b44b34ea
      { @selector( NSObject), @selector( _NSNumber) },      // e9e78cbd,05c62dfe
      { @selector( NSObject), @selector( _NSSet) },      // e9e78cbd,ef0424f3
      { @selector( NSObject), @selector( _NSString) },      // e9e78cbd,f080ce2a
      { @selector( NSObject), @selector( _NSTimeZone) },      // e9e78cbd,32e5e7e4
      { @selector( NSObject), @selector( _NSValue) },      // e9e78cbd,227bb908
      { @selector( NSPropertyListSerialization), MULLE_OBJC_NO_CATEGORYID },      // 6a96a095,00000000
      { @selector( NSScanner), MULLE_OBJC_NO_CATEGORYID },      // baff1492,00000000
      { @selector( NSSet), @selector( NSArray) },      // 9a5ad940,55e6335f
      { @selector( NSSet), @selector( NSCoder) },      // 9a5ad940,57eb31d7
      { @selector( NSSet), @selector( NSMutableSet) },      // 9a5ad940,e6cae1ee
      { @selector( NSSet), MULLE_OBJC_NO_CATEGORYID },      // 9a5ad940,00000000
      { @selector( NSSortDescriptor), @selector( NSCoder) },      // 115836cf,57eb31d7
      { @selector( NSSortDescriptor), MULLE_OBJC_NO_CATEGORYID },      // 115836cf,00000000
      { @selector( NSString), @selector( ClassCluster) },      // 85e3fa43,9fe7683b
      { @selector( NSString), @selector( Components) },      // 85e3fa43,4dd10b69
      { @selector( NSString), @selector( Escaping) },      // 85e3fa43,9b2b4859
      { @selector( NSString), @selector( Locale) },      // 85e3fa43,8b50377b
      { @selector( NSString), @selector( NSCharacterSet) },      // 85e3fa43,b452f5f7
      { @selector( NSString), @selector( NSCoder) },      // 85e3fa43,57eb31d7
      { @selector( NSString), @selector( NSData) },      // 85e3fa43,7d1455e8
      { @selector( NSString), @selector( NSMutableString) },      // 85e3fa43,fcaa2a91
      { @selector( NSString), @selector( NSPropertyListParsing) },      // 85e3fa43,d53dd685
      { @selector( NSString), @selector( NSSearch) },      // 85e3fa43,47c61184
      { @selector( NSString), @selector( PropertyListPrinting) },      // 85e3fa43,1cb22f11
      { @selector( NSString), @selector( Sprintf) },      // 85e3fa43,af844695
      { @selector( NSString), MULLE_OBJC_NO_CATEGORYID },      // 85e3fa43,00000000
      { @selector( NSThread), @selector( NSDate) },      // 645eeb40,7d1455ec
      { @selector( NSThread), @selector( NSDictionary) },      // 645eeb40,ca46313c
      { @selector( NSThread), @selector( NSNotification) },      // 645eeb40,18e88d95
      { @selector( NSTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 4bf7bd11,00000000
      { @selector( NSUnarchiver), MULLE_OBJC_NO_CATEGORYID },      // bc40ee49,00000000
      { @selector( NSValue), @selector( NSCoder) },      // b732699b,57eb31d7
      { @selector( NSValue), @selector( NSString) },      // b732699b,85e3fa43
      { @selector( NSValue), MULLE_OBJC_NO_CATEGORYID },      // b732699b,00000000
      { @selector( _MulleObjC03LengthASCIIString), MULLE_OBJC_NO_CATEGORYID },      // ca173298,00000000
      { @selector( _MulleObjC07LengthASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 1358dedc,00000000
      { @selector( _MulleObjC11LengthASCIIString), MULLE_OBJC_NO_CATEGORYID },      // d20ecbd7,00000000
      { @selector( _MulleObjC15LengthASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b490b473,00000000
      { @selector( _MulleObjCASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b17891ed,00000000
      { @selector( _MulleObjCAllocatorASCIIString), MULLE_OBJC_NO_CATEGORYID },      // b3b1aa1a,00000000
      { @selector( _MulleObjCAllocatorData), MULLE_OBJC_NO_CATEGORYID },      // 663063e8,00000000
      { @selector( _MulleObjCAllocatorUTF16String), MULLE_OBJC_NO_CATEGORYID },      // c3a3ab65,00000000
      { @selector( _MulleObjCAllocatorUTF32String), MULLE_OBJC_NO_CATEGORYID },      // a256bdf3,00000000
      { @selector( _MulleObjCArrayEnumerator), MULLE_OBJC_NO_CATEGORYID },      // d143a2c2,00000000
      { @selector( _MulleObjCBufferedDataInputStream), MULLE_OBJC_NO_CATEGORYID },      // 0d571f10,00000000
      { @selector( _MulleObjCBufferedDataOutputStream), MULLE_OBJC_NO_CATEGORYID },      // ef16bfd3,00000000
      { @selector( _MulleObjCCheatingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 93c7de3c,00000000
      { @selector( _MulleObjCConcreteArray), @selector( NSCoder) },      // 429b8f4b,57eb31d7
      { @selector( _MulleObjCConcreteArray), MULLE_OBJC_NO_CATEGORYID },      // 429b8f4b,00000000
      { @selector( _MulleObjCConcreteBitmapCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // b0c16d52,00000000
      { @selector( _MulleObjCConcreteCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 7a6cbb3b,00000000
      { @selector( _MulleObjCConcreteData), MULLE_OBJC_NO_CATEGORYID },      // 1f717c6c,00000000
      { @selector( _MulleObjCConcreteDictionary), MULLE_OBJC_NO_CATEGORYID },      // 994b8bd0,00000000
      { @selector( _MulleObjCConcreteMutableData), MULLE_OBJC_NO_CATEGORYID },      // 07ff08b2,00000000
      { @selector( _MulleObjCConcreteMutableDictionary), MULLE_OBJC_NO_CATEGORYID },      // 12b624de,00000000
      { @selector( _MulleObjCConcreteMutableSet), MULLE_OBJC_NO_CATEGORYID },      // b136229a,00000000
      { @selector( _MulleObjCConcreteRangeCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 40b6b334,00000000
      { @selector( _MulleObjCConcreteSet), MULLE_OBJC_NO_CATEGORYID },      // 9b80027c,00000000
      { @selector( _MulleObjCConcreteValue), @selector( NSCoder) },      // f6981437,57eb31d7
      { @selector( _MulleObjCConcreteValue), MULLE_OBJC_NO_CATEGORYID },      // f6981437,00000000
      { @selector( _MulleObjCDictionary), MULLE_OBJC_NO_CATEGORYID },      // 5c32cfb5,00000000
      { @selector( _MulleObjCDictionaryKeyEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 349fca60,00000000
      { @selector( _MulleObjCDictionaryObjectEnumerator), MULLE_OBJC_NO_CATEGORYID },      // ba82797a,00000000
      { @selector( _MulleObjCDoubleNumber), @selector( NSString) },      // dc33cb0d,85e3fa43
      { @selector( _MulleObjCDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // dc33cb0d,00000000
      { @selector( _MulleObjCEightBytesData), MULLE_OBJC_NO_CATEGORYID },      // 4268aeab,00000000
      { @selector( _MulleObjCEmptyArray), MULLE_OBJC_NO_CATEGORYID },      // dc15d003,00000000
      { @selector( _MulleObjCEmptySet), MULLE_OBJC_NO_CATEGORYID },      // 0b68bf04,00000000
      { @selector( _MulleObjCEmptyString), MULLE_OBJC_NO_CATEGORYID },      // 13a773e7,00000000
      { @selector( _MulleObjCGenericASCIIString), MULLE_OBJC_NO_CATEGORYID },      // ae0c6852,00000000
      { @selector( _MulleObjCGenericUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 0b4cae5d,00000000
      { @selector( _MulleObjCGenericUTF32String), MULLE_OBJC_NO_CATEGORYID },      // dc84ee6b,00000000
      { @selector( _MulleObjCInt16Number), MULLE_OBJC_NO_CATEGORYID },      // 6fca9882,00000000
      { @selector( _MulleObjCInt32Number), MULLE_OBJC_NO_CATEGORYID },      // c4c92a2c,00000000
      { @selector( _MulleObjCInt64Number), MULLE_OBJC_NO_CATEGORYID },      // e3f49f9d,00000000
      { @selector( _MulleObjCInt8Number), MULLE_OBJC_NO_CATEGORYID },      // d674370b,00000000
      { @selector( _MulleObjCLocalTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 9b685e8f,00000000
      { @selector( _MulleObjCLongDoubleNumber), @selector( NSString) },      // 82e6ea4f,85e3fa43
      { @selector( _MulleObjCLongDoubleNumber), MULLE_OBJC_NO_CATEGORYID },      // 82e6ea4f,00000000
      { @selector( _MulleObjCMediumData), MULLE_OBJC_NO_CATEGORYID },      // 850699c0,00000000
      { @selector( _MulleObjCMemoryDataInputStream), MULLE_OBJC_NO_CATEGORYID },      // a2abd19c,00000000
      { @selector( _MulleObjCPropertyListReader), MULLE_OBJC_NO_CATEGORYID },      // 5f6f56ff,00000000
      { @selector( _MulleObjCReferencingASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 62ac41ad,00000000
      { @selector( _MulleObjCSet), MULLE_OBJC_NO_CATEGORYID },      // 6c4a19bf,00000000
      { @selector( _MulleObjCSetEnumerator), MULLE_OBJC_NO_CATEGORYID },      // 41aabe4d,00000000
      { @selector( _MulleObjCSharedASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 39568c40,00000000
      { @selector( _MulleObjCSharedData), MULLE_OBJC_NO_CATEGORYID },      // f173b26a,00000000
      { @selector( _MulleObjCSharedUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 5125ac3b,00000000
      { @selector( _MulleObjCSharedUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 8c5cdcb5,00000000
      { @selector( _MulleObjCSixteenBytesData), MULLE_OBJC_NO_CATEGORYID },      // d1d33ea0,00000000
      { @selector( _MulleObjCTaggedPointerChar5String), MULLE_OBJC_NO_CATEGORYID },      // e5265a16,00000000
      { @selector( _MulleObjCTaggedPointerChar7String), MULLE_OBJC_NO_CATEGORYID },      // 5c2b0d90,00000000
      { @selector( _MulleObjCTaggedPointerIntegerNumber), @selector( NSCoder) },      // 7505d5b1,57eb31d7
      { @selector( _MulleObjCTaggedPointerIntegerNumber), MULLE_OBJC_NO_CATEGORYID },      // 7505d5b1,00000000
      { @selector( _MulleObjCTinyASCIIString), MULLE_OBJC_NO_CATEGORYID },      // 187c1c2f,00000000
      { @selector( _MulleObjCTinyData), MULLE_OBJC_NO_CATEGORYID },      // 10a5f233,00000000
      { @selector( _MulleObjCUInt32Number), @selector( NSString) },      // 4876770d,85e3fa43
      { @selector( _MulleObjCUInt32Number), MULLE_OBJC_NO_CATEGORYID },      // 4876770d,00000000
      { @selector( _MulleObjCUInt64Number), @selector( NSString) },      // c9a449b0,85e3fa43
      { @selector( _MulleObjCUInt64Number), MULLE_OBJC_NO_CATEGORYID },      // c9a449b0,00000000
      { @selector( _MulleObjCUTF16String), MULLE_OBJC_NO_CATEGORYID },      // 59aea06e,00000000
      { @selector( _MulleObjCUTF32String), MULLE_OBJC_NO_CATEGORYID },      // 8125da64,00000000
      { @selector( _MulleObjCUTF8StreamReader), MULLE_OBJC_NO_CATEGORYID },      // 019bce09,00000000
      { @selector( _MulleObjCZeroBytesData), MULLE_OBJC_NO_CATEGORYID },      // bce2b0c8,00000000
      { @selector( _NSGMTTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 50cec3ce,00000000
