#
# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/NSArray
src/NSDictionary
src/NSSet
)

set( PRIVATE_HEADERS
src/NSArray/_MulleObjCConcreteArray-Private.h
src/NSArray/NSArray-Private.h
src/NSDictionary/_MulleObjCDictionary-Private.h
src/NSSet/_MulleObjCSet-Private.h
src/import-private.h
src/include-private.h
)

set( PUBLIC_HEADERS
src/MulleObjCContainerFoundation.h
src/MulleObjCLoader+MulleObjCContainerFoundation.h
src/MullePreempt.h
src/NSArray/_MulleObjCArrayEnumerator.h
src/NSArray/_MulleObjCConcreteArray.h
src/NSArray/_MulleObjCEmptyArray.h
src/NSArray/NSArray+NSCoder.h
src/NSArray/_NSArrayPlaceholder.h
src/NSArray/NSArray.h
src/NSArray/NSEnumerator+NSArray.h
src/NSArray/NSMutableArray.h
src/NSArray/mulle-qsort-pointers.h
src/NSDictionary/_MulleObjCConcreteDictionary.h
src/NSDictionary/_MulleObjCConcreteMutableDictionary.h
src/NSDictionary/_MulleObjCDictionary.h
src/NSDictionary/_MulleObjCEmptyDictionary.h
src/NSDictionary/NSDictionary+NSArray.h
src/NSDictionary/NSDictionary+NSCoder.h
src/NSDictionary/_NSDictionaryPlaceholder.h
src/NSDictionary/NSDictionary.h
src/NSDictionary/NSMutableDictionary+NSArray.h
src/NSDictionary/_NSMutableDictionaryPlaceholder.h
src/NSDictionary/NSMutableDictionary.h
src/NSDictionary/NSThread+NSMutableDictionary.h
src/NSDictionary/ns-map-table.h
src/NSEnumerator.h
src/NSSet/_MulleObjCConcreteMutableSet.h
src/NSSet/_MulleObjCConcreteSet.h
src/NSSet/_MulleObjCEmptySet.h
src/NSSet/_MulleObjCSet.h
src/NSSet/NSMutableSet+NSArray.h
src/NSSet/_NSMutableSetPlaceholder.h
src/NSSet/NSMutableSet.h
src/NSSet/NSSet+NSArray.h
src/NSSet/NSSet+NSCoder.h
src/NSSet/_NSSetPlaceholder.h
src/NSSet/NSSet.h
src/NSSet/ns-hash-table.h
src/import.h
src/include.h
)

